version: 2

jobs:
  # Check source format
  ubuntu16.04:
    docker:
      - image: gcr.io/wizzie-registry/prozzie-test-env:ubuntu-16.04
    environment:
      PROZZIE_PREFIX: /opt/prozzie
      KCOV_FLAGS: --include-path=/opt/prozzie,/root/project/setups
      KCOV_OUT: /tmp/coverage
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install prozzie & dependencies
          environment:
            CLIENT_API_KEY: prozzieapi
            ZZ_HTTP_ENDPOINT: localhost
          # yes will fail
          command: >
            set +o pipefail;
            yes |
            env PREFIX="${PROZZIE_PREFIX}" INTERFACE_IP=${HOSTNAME}
            kcov ${KCOV_FLAGS} install_cov setups/linux_setup.sh
      # Circleci forbids us to communicate with remote docker host, so we need
      # to make kafka find it's own address as the exported broker...
      - run:
          name: Make kafka find itself
          command: >-
            "${PROZZIE_PREFIX}/bin/prozzie" compose exec -T kafka
            bash -c "printf '%s %s\n' '127.0.0.1' \"${HOSTNAME}\" >> /etc/hosts"

      # ...and to simulate external kafka port forwarding
      - run:
          name: Expose kafka port
          background: true
          # Need to use docker -e because a socat parsing error
          command: >-
              socat TCP-LISTEN:9092,reuseaddr,fork
              EXEC:'docker run --network prozzie_default -i alpine/socat
              STDIO TCP\:prozzie_kafka_1\:9092'
      - run:
          name: Run actual tests
          command: cd tests; make coverage
      - run:
          name: Merge all coverage
          command: kcov --merge ${KCOV_OUT} install_cov tests/coverage.html
      - store_artifacts:
          path: '/tmp/coverage'

workflows:
  version: 2
  tests:
    jobs:
      - ubuntu16.04
