version: '3.6'

services:
  f2k:
    image: gcr.io/wizzie-registry/prozzie-f2k:1.1.0
    restart: always
    depends_on:
      - kafka
    ports:
      - 2055:2055
    env_file:
      - ${PREFIX}/etc/prozzie/envs/f2k.env
    environment:
      F2K_NTHREADS: 3
      RDKAFKA_QUEUE_BUFFERING_MAX_MS: 1000
