version: '3'
services:
  http2k:
    image: gcr.io/wizzie-registry/n2kafka:1.99-10
    restart: always
    depends_on:
      - kafka
    ports:
      - 7980:7980
    environment:
      KAFKA_BROKERS: kafka
