version: '3.6'

services:
  http2k:
    image: gcr.io/wizzie-registry/n2kafka:2.1.1
    restart: always
    depends_on:
      - kafka
    ports:
      - 7980:7980
    environment:
      KAFKA_BROKERS: kafka
