version: '3.6'

services:
  meraki:
    image: gcr.io/wizzie-registry/n2kafka:2.1.1
    restart: always
    depends_on:
      - kafka
    ports:
      - 2057:2057
    environment:
      KAFKA_BROKERS: kafka
      DECODER: meraki
      LISTENER_PORT: 2057
      DEFAULT_TOPIC: meraki
