version: '3.6'

volumes:
  # Empty volume as placeholder in case that no custom mibs specified
  "monitor_custom_mibs":

services:
  monitor:
    image: gcr.io/wizzie-registry/prozzie-monitor:1.2.0
    restart: always
    depends_on:
      - kafka
    ports:
      - 162:162
    env_file:
      - ${PREFIX}/etc/prozzie/envs/monitor.env
    environment:
      KAFKA_BROKERS: 'kafka'

    volumes:
      - "${MONITOR_CUSTOM_MIB_PATH:-monitor_custom_mibs}:/root/.snmp/mibs:ro"
