version: '3'

volumes:
  # Empty volume as placeholder in case that no custom mibs specified
  "monitor_custom_mibs":

services:
  monitor:
    image: gcr.io/wizzie-registry/prozzie-monitor:1.2.0
    restart: always
    depends_on:
      - kafka
    ports:
      - "${MONITOR_TRAPS_PORT:-162}:${MONITOR_TRAPS_PORT:-162}/udp"
    environment:
      REQUESTS_TIMEOUT: ${MONITOR_REQUEST_TIMEOUT:-25}
      KAFKA_BROKERS: 'kafka'
      KAFKA_TOPIC: "${MONITOR_KAFKA_TOPIC:-monitor}"
      SENSORS_ARRAY: "${MONITOR_SENSORS_ARRAY:-''}"
      TRAPS_PORT: "${MONITOR_TRAPS_PORT:-''}"

    volumes:
      - "${MONITOR_CUSTOM_MIB_PATH:-monitor_custom_mibs}:/root/.snmp/mibs:ro"
