version: '3.6'

services:
  sfacctd:
    image: gcr.io/wizzie-registry/prozzie-sfacctd:1.6.2
    restart: always
    depends_on:
      - kafka
    ports:
      - 6343:6343/udp
    env_file:
      - ${PREFIX}/etc/prozzie/envs/f2k.env
    environment:
      KAFKA_BROKERS: "kafka"
